version: '3.9'

services:

  django:
    image: soundwav_production
    container_name: soundwav_production_django
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        environment: production
    restart: always
    env_file:
      - ../.env/.env.production
    ports:
      - "80:8000"
    volumes:
      - ../:/backend
    command: sh -c "chmod +x ./entrypoint.sh && sh ./entrypoint.sh"
